name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: Build
      run: go build -ldflags "-H=windowsgui" -o tempmanager.exe -v ./...
    - uses: actions/upload-artifact@v2
    - uses: actions/upload-artifact@v2
      with:
        name: tempmanager
        path: tempmanager.exe

